brace_style = "AlwaysNextLine"
fn_call_width = 120
max_width = 120
chain_width = 80
format_code_in_doc_comments = true
match_block_trailing_comma = true
newline_style = "Unix"
normalize_comments = true
group_imports = "StdExternalCrate"
reorder_modules = true
wrap_comments = true
